---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml
    role-file: molecule/default/requirements.yml
driver:
  name: podman
platforms:
  - name: mol-common-arch
    image: docker.io/gliech/docker-archlinux-ansible:branch-master
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-fedora38
    image: docker.io/geerlingguy/docker-fedora38-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-fedora37
    image: docker.io/geerlingguy/docker-fedora37-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-fedora36
    image: docker.io/geerlingguy/docker-fedora36-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-fedora35
    image: docker.io/geerlingguy/docker-fedora35-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-rocky9
    image: docker.io/geerlingguy/docker-rockylinux9-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-rocky8
    image: docker.io/geerlingguy/docker-rockylinux8-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-debian12
    image: docker.io/geerlingguy/docker-debian12-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-debian11
    image: docker.io/geerlingguy/docker-debian11-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-ubuntu2204
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: mol-common-ubuntu2004
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
verifier:
  name: ansible
scenario:
  check_sequence:
    - dependency
    - create
    - prepare
    - converge
    - check
  destroy_sequence:
    - dependency
    - destroy
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
