---
- name: Prepare Archlinux
  hosts: all
  tasks:
    - name: Initialize package cache
      package:
        update_cache: yes
        upgrade: yes
      become: yes
      when: ansible_pkg_mgr in ['apt', 'pacman']
    # The existance of pip-installed cryptography libraries can interfere
    # with the versions that this module  installs through the system package
    # manager. Archlinux has the library already installed through pacman
    # though, so removing it in pip would break the system.
    - name: Remove python-cryptography
      pip:
        name: cryptography
        state: absent
      when: ansible_os_family != 'Archlinux'
