---
- name: Verify
  hosts: all
  tasks:
    - name: Test list functionality in yum module
      ansible.builtin.package:
        list:
      become: yes
      when: ansible_pkg_mgr in ['yum', 'dnf']

    - name: Test availability of cryptography module
      community.crypto.openssl_privatekey:
        path: ~/test.key
        type: ECC
        curve: secp384r1
      register: output

    - name: Test availability of mkfs.btrfs
      community.general.filesystem:
        dev: "/dev/null"
        fstype: btrfs
      # btrfs is not supported under most RedHat systems
      when: ansible_os_family != "RedHat" or ansible_distribution == "Fedora"
      check_mode: true
