---
- name: Verify
  hosts: all
  tasks:
    - name: test list functionality in yum module
      package:
        list:
      become: yes
      when: ansible_pkg_mgr in ['yum', 'dnf']
    - name: test availability of cryptography module
      community.crypto.openssl_privatekey:
        path: ~/test.key
        type: ECC
        curve: secp384r1
      register: output
